
export enum ErrorCode {
  VALIDATION_ERROR = "COMMON_001",
  UNAUTHORIZED = "AUTH_001",
  FORBIDDEN = "AUTH_002",
  USER_NOT_FOUND = "USER_001",
  EMAIL_ALREADY_EXISTS = "USER_002",
  INTERNAL_ERROR = "SYS_001",
}
